services:

  elrond:
    image: alpine
    container_name: elrond
    command: >
      sh -c 'echo "Summons to the community" &&
             echo $$(date +%s) > /shared/call_timestamp.txt &&
             tail -f /dev/null'
    volumes:
      - summons_volume:/shared
    networks:
      - rivendel_net

volumes:
  summons_volume:
    name: summons_volume

